{
    "name": "G2P Self Service Portal: Rest API",
    "category": "G2P",
    "version": "15.0.0.0.1",
    "sequence": 1,
    "author": "OpenG2P",
    "website": "https://github.com/OpenG2P/openg2p-self-service-portal",
    "license": "Other OSI approved licence",
    "development_status": "Production/Stable",
    "depends": [
        "base",
        "component",
        "base_rest",
        "pydantic",
        "extendable",
        "base_rest_pydantic",
        "base_rest_auth_user_service",
        "g2p_programs",
        "g2p_self_service_base",
    ],
    "external_dependencies": {"python": ["extendable-pydantic", "pydantic"]},
    "data": [],
    "assets": {
        "web.assets_backend": [],
        "web.assets_qweb": [],
    },
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
